version: '3'
services:
    nginx:
        image: nginx:latest
        # 端口映射
        ports:
            - "80:80"
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "./conf.d:/etc/nginx/conf.d"
            - "./html:/var/www/html"
        # 容器名称
        container_name: "compose-nginx"
    php:
        build: ./php-mysqli
        ports:
            - "9000:9000"
        volumes:
            - "./html:/var/www/html"
        depends_on:
            - mysql
        container_name: "compose-php"
        
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        # mysqlの起動時に文字コードを指定
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0
        volumes:
            - ./db:/var/lib/mysql # ホストOSのdbフォルダ内にmysqlコンテナのDBの内容を保存
        environment:
            - MYSQL_ROOT_PASSWORD=root # mysqlのルートパスワードを設定
            - MYSQL_DATABASE=sample # デフォルトで作成するデータベース名を設定
            - MYSQL_USER=testuser # デフォルトで作成するDBユーザー名を設定a
            - "TZ=Asia/Tokyo" # タイムゾーンを設定
        container_name: "compose-mysql"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin # phpmyadminのコンテナイメージをそのまま利用
        environment:
            - PMA_HOST=mysql # 上記で作成したmysqlコンテナに接続
        depends_on:
            - mysql # 上記で作成したmysqlコンテナとリンクする
        ports:
            - 8888:80 # ホストの8888番ポートをphpmyadminコンテナの80番ポートに転送
        volumes:
            - ./pma/sessions:/sessions # ホストOSのpmaディレクトリ内にphpmyadminコンテナのセッションファイルを保存